name: example
description: example for flutter_binding.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-152 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  auto_binding: ^2.0.13
  auto_binding:
    path: ../auto_binding

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


