name: auto_binding
description: AutoBinding is a lightweight MVVM bidirectional binding state management framework for data sharing and synchronization.
version: 2.1.4
homepage: 'https://github.com/ellisez/AutoBinding'
topics:
  - mvvm
  - bidirectional-binding
  - partial-refresh
  - codegen

environment:
  sdk: ^3.5.0-152

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.0-main.5

dev_dependencies:
  flutter_lints: ^4.0.0
