name: auto_binding
description: AutoBinding is a lightweight MVVM bidirectional binding state management framework for data sharing and synchronization.
version: 2.0.2
homepage: 'https://github.com/ellisez/DataBinding'
topics:
  - mvvm
  - partial-refresh
  - codegen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
