name: auto_binding
description: AutoBinding is a lightweight MVVM bidirectional binding state management framework for data sharing and synchronization.
version: 2.0.6
homepage: 'https://github.com/ellisez/AutoBinding'
topics:
  - mvvm
  - bidirectional-binding
  - partial-refresh
  - codegen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
  flutter_lints: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
