name: auto_binding_ui
description: "UI library for AutoBinding."
version: 0.0.1
homepage: ''

environment:
  sdk: '>=3.5.0-152 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
