name: model_binding
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  map_model: ^1.0.3
