name: model_binding
description: ModelBinding is a Widget data src.binding framework implemented using MapModel, and its biggest advantage is that modifying data can automatically refresh corresponding Widgets.
version: 2.0.0
homepage: 'https://github.com/ellisez/ModelBinding'
topics:
  - mvvm
  - json
  - codegen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
