name: model_binding_builder
description: ModelBinding is a Widget data src.binding framework implemented using MapModel, and its biggest advantage is that modifying data can automatically refresh corresponding Widgets.
version: 1.0.10
homepage: 'https://github.com/ellisez/ModelBinding'
topics:
  - mvvm
  - build-runner
  - json
  - codegen

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.2
  map_model_builder: ^1.0.17
  model_binding: ^1.0.9

dev_dependencies:
  build_test: any
  build_web_compilers: any

