name: model_binding_builder
description: Deprecated, see ModelBinding v2.
version: 2.0.0
homepage: 'https://github.com/ellisez/ModelBinding'
topics:
  - mvvm
  - build-runner
  - json
  - codegen

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.2
  analyzer: ^5.12.0
  map_model_builder: ^1.0.22
  model_binding: ^1.0.18

dev_dependencies:
  build_test: any
  build_web_compilers: any

