name: model_binding_builder
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  model_binding:
    path: ../model_binding
  map_model_builder: ^1.0.9

dev_dependencies:
  build_test: any
  build_web_compilers: any

